SPOTIFY_CLIENT_ID=67a593c980d846268d278798d6434fcf
SPOTIFY_CLIENT_SECRET=3fb28c59661e402ba40c3af3b9b98b06

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3